chore(chore): save state

diff --git a/apps/web/Dockerfile b/apps/web/Dockerfile
--- a/apps/web/Dockerfile
+++ b/apps/web/Dockerfile
@@ -5,10 +5,8 @@ ARG BUILD_FLAG
 
 WORKDIR /app/builder
 
-# RUN ls apps/web/.next -a
-RUN npx nx run web:build -d || echo "nx run web:build failed"
-# RUN ls apps/web/.next -a
-# RUN ls apps/web/.next/standalone
+RUN npx nx run web:build || echo "nx run web:build failed"
+RUN ls apps/web/.next
 
 FROM node:lts-alpine AS runner
 
